# Generated by Django 4.2.23 on 2025-07-31 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_images/"
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=500)),
                (
                    "skills",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated list of skills",
                        max_length=255,
                    ),
                ),
                (
                    "experience",
                    models.TextField(
                        blank=True, help_text="Brief description of your experience"
                    ),
                ),
                ("website", models.URLField(blank=True, max_length=255)),
                ("github", models.URLField(blank=True, max_length=255)),
                ("twitter", models.URLField(blank=True, max_length=255)),
                ("linkedin", models.URLField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
