# Generated by Django 4.2.23 on 2025-07-31 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0002_mcptoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light Mode"),
                            ("dark", "Dark Mode"),
                            ("system", "System Default"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                (
                    "font_size",
                    models.CharField(
                        choices=[
                            ("small", "Small"),
                            ("medium", "Medium"),
                            ("large", "Large"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "reduced_motion",
                    models.BooleanField(
                        default=False, help_text="Reduce animation effects"
                    ),
                ),
                (
                    "high_contrast",
                    models.BooleanField(
                        default=False, help_text="Enable high contrast mode"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
