# Generated by Django 4.2.23 on 2025-07-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="content_html",
            field=models.TextField(blank=True, editable=False),
        ),
    ]
