# Generated by Django 4.2.23 on 2025-07-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solutions", "0002_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="solution",
            name="summary",
            field=models.TextField(
                blank=True,
                editable=False,
                help_text="AI-generated summary of the solution",
            ),
        ),
    ]
